---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: lofocats
    component: migrate
  name: lofocats-migrate
spec:
  template:
    metadata:
      labels:
        app: lofocats
        component: migrate
    spec:
      containers:
      - image: maxbrunet/lofocats_api:latest
        name: lofocats-migrate
        command: ["rake", "db:migrate"]
        env:
        - name: RAILS_ENV
          value: production
        envFrom:
        - secretRef:
            name: lofocats-api-database-url
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 2  # non-root user
      restartPolicy: OnFailure
